"""empty message

Revision ID: 86078a8ca41a
Revises: 
Create Date: 2021-06-01 18:57:47.737339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86078a8ca41a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('dependent', sa.Integer(), nullable=False),
    sa.Column('Edu_Level', sa.Integer(), nullable=False),
    sa.Column('marige', sa.Integer(), nullable=False),
    sa.Column('income', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
